### ISSUE TITLE
Dynamic module positions

### ISSUE THREAD

**Issue by laoneo** [Digital-Peak-Incubator/tpl_tauristar#100]
Dynamic module positions.

**Comment by ufuk-avcu** [comment]
https://github.com/Digital-Peak-Incubator/tpl_tauristar/commit/df3e6951f574ed128b618022e7f0acd1f5748fb3

**Comment by zero-24** [comment]
@ufuk-avcu ca you have a look here: https://github.com/Digital-Peak-Incubator/tpl_tauristar/compare/Daynamic-Modul-Positions...zero-24:codestyle-dmp?expand=1 ? I try to test it now

**Comment by zero-24** [comment]
maybe we can send the chnages as pull request? This would make it a lot easier to test ?

**Comment by zero-24** [comment]
It works but we need to apply my branche else we get a PHP error if nothing is set in the backend. Also i'm not sure about the path where we save the templatedetails-modules.xml maybe we use a new sub folder `subform` or `settings`?

**Comment by zero-24** [comment]
Closing as we have the PR at #101
