### ISSUE TITLE
Drop <jdoc:include

### ISSUE THREAD

**Issue by dgt41** [Digital-Peak-Incubator/tpl_tauristar#106]
`<jdoc:include type="whatever" />` is just a wrapper to a simple `echo blabla`

Check https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/html.php#L652-L706

This is what I use in my templates:

``` html
<?php echo $this->getBuffer('modules', 'slideshow', array('slideshow', 'html5')); ?>
```

which is the same as joomla's:

``` html
<jdoc:include type="slideshow" />
```

But is freaking faster as I don't parse/check/replace (of course I override all the renderer part of joomla but that's not the point here)

**Comment by laoneo** [comment]
Why did you open that issue? Where do we use it?

**Comment by mbabker** [comment]
Take it to core, not something to be discussed in a small arena like this.
