### ISSUE TITLE
com_content/category

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#13]
- [x] **blog.php** No adaption needed.
- [x] **blog_children.php** No adaption needed.
- [x] **blog_item.php** No adaption needed.
- [x] **blog_links.php** No adaption needed.
- [x] **default.php** No adaption needed.
- [x] **default_articles.php** See PR #84.
- [x] **default_children** No adaption needed.

**Comment by laoneo** [comment]
View is reviewed and PR's created.
