### ISSUE TITLE
com_content/featured

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#14]
* [x] **default.php** Done with default.bs3.php (0dd220744ea3064dd4041629eea574e87f7b0ac1 and 7636d0f9d9201352d0cbdc9c061c56ccb1e8e2fe).
* [x] **default_item.php** No migration is needed as it has already the correct classes.
* [x] **default_links.php** No migration is needed as it has already the correct classes. See comment below.

**Comment by laoneo** [comment]
default_item.php
No migration is needed as it has already the correct classes.

With protostar it looks like:
![image](https://cloud.githubusercontent.com/assets/251072/16652847/8d4ad7f4-444d-11e6-8b9f-1591a1608ca9.png)

With tauristar it looks like:
![image](https://cloud.githubusercontent.com/assets/251072/16652920/ff6f4de2-444d-11e6-9226-92a678f1084c.png)
