### ISSUE TITLE
JHtml Overrides

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#68]

**Comment by dneukirchen** [comment]
duplicate of #80

**Comment by laoneo** [comment]
I would not close this one as thus issue is about coding, where #80 is about docu. Probably we need to create for every JHtml class a layout and an override.

**Comment by dneukirchen** [comment]
I agree. We have to create JLayouts for the Html parts of every JHtml class. 
I closed this issue, because i think its better to have small  issues (one for every JHtml class) instead of a giant "JHtml Overrides" Issue.

**Comment by yvesh** [comment]
Sounds reasonable. Added a label for JHtml Overrides too, so they can be easier grouped.

**Comment by laoneo** [comment]
Can't see the new label? Hope we don't forget to add the issue for JHtml :see_no_evil:

**Comment by yvesh** [comment]
@laoneo added, that's the issue when you do 30 things at the same time

**Comment by laoneo** [comment]
I know that feeling, gave it an unique color, we are soon running out of colors for our labels.
