### ISSUE TITLE
mod_breadcrumbs

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#70]

**Comment by zero-24** [comment]
Looks good here, nothing needs to be changed:

### tauristar
![tauristar](https://cloud.githubusercontent.com/assets/2596554/16850873/3dcc315a-4a01-11e6-9dba-87631bf92db4.JPG)

### protostar
![protostar](https://cloud.githubusercontent.com/assets/2596554/16850878/44eeb6ba-4a01-11e6-82f6-7be841bc1c06.JPG)

So what we need to do next? Close this issue or copy the view to the tauristar template?
