### ISSUE TITLE
mod_menu

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#74]
Mod_menu needs new navigation classes for BS3.

**Comment by laoneo** [comment]
Done with commit b9ec5c5ffa8ef9e61f92807f795b5b43dfb5686a and 0da931f037d2bbff1582c2191403c52f15af6465 directly on the default branch. Must be done trough a PR in the future, but it is important to have the start in a good shape :-)
