### ISSUE TITLE
Fix code style errors

### ISSUE THREAD

**Issue by laoneo** [Digital-Peak-Incubator/tpl_tauristar#82]
~~Somehow the JApplicationSiteTest tests do fail https://travis-ci.org/Digital-Peak-Incubator/tpl_tauristar/builds/141969052.~~

Was a test from something different. The issue should deal with code styl errors. Sorry for the confusion.

**Comment by yvesh** [comment]
@laoneo The tests fail because of php code style in the template. PHPCS is only run at PHP 5.6, this is the reason every other test passes.
