### ISSUE TITLE
Switch to SASS compiler in Tauristar

### ISSUE THREAD

**Issue by dneukirchen** [Digital-Peak-Incubator/tpl_tauristar#83]
I know... not this question... not again... ;D  Sass or Less?

Im ok with both of them, but i would prefer to use sass:

* More popular: https://www.google.com/trends/explore#q=%2Fm%2F054k6n_%2C%20%2Fm%2F0gjd0jv&cmpt=q&tz=Etc%2FGMT%2B7
* Cleaner syntax and better support for features like loops etc.
* Good Tooling (compass)
* Bootstrap 4 switched to sass
* Better performance on medium and large projects

Decision was made on our second meeting that we are going to use SASS, https://docs.google.com/document/d/1-Yf9cMbN-pNEDyhIcrKQ62dRUUWThn2DYc-BWe304Jo.

**Comment by laoneo** [comment]
Closing this issue as we have the PR #96 for it.
