### ISSUE TITLE
Include CSScompressor-Option in Template

### ISSUE THREAD

**Issue by designbengel** [Digital-Peak-Incubator/tpl_tauristar#92]
Is there a way to include CSS Compressing option? Like the Less compiler but one step further? template.min.css?

:)

**Comment by laoneo** [comment]
Would stripping out spaces, tabs and new lines help?

**Comment by zero-24** [comment]
just in the template? why not in the template manger? Or i missunderstanding it?

**Comment by designbengel** [comment]
Yes, of course, it would be cool as a part of the template manager

**Comment by laoneo** [comment]
What do you mean in the template manager? Not an option in the template? IMO this belongs to the template. Do I miss here something?

**Comment by zero-24** [comment]
@laoneo i mean something similiar to the less compiler in the template manger.

If you edit a css files you would be able to run the generate script once so there is no need to run that in the frontend user context.

Per default the template comes with a minified version of the css file (so no conversion / minifing needed in the fronteduser context.).

**Comment by laoneo** [comment]
If you edit a CSS file no compiling is needed at all. IMO the user shouldn't care about this at all. A template should not come with a (minfied) CSS file. If a file change is detected or no cache file is present, then the compiling should be triggered automatically. Do site admins really need to care about compiling and compression and so on?

**Comment by yvesh** [comment]
I agree with Allon, minifying should be done automatically, once there are changes (this is really easy to detect with filemtime and naming files with with the md5 sum of it).. maybe with a setting to disable it.. there is no reason to not do that by default for CSS

**Comment by laoneo** [comment]
Can this issue being closed as in PR #96 a mode parameter exists? If this parameter is set to development, then on every page request the CSS file is compiled while in production only if the file doesn't exist.

To answer the initial question. Compression is done in production mode with PR #96.

**Comment by cpfeifer** [comment]
I would recommend this: http://leafo.net/scssphp/ - it's the SCSS version of the LESS compiler in the Joomla core.

The attached image shows the 4 options that are usually available in compilers by default. I don't believe it would be difficult to modify them if necessary, but there are output options available by default.
![scss-output-options](https://cloud.githubusercontent.com/assets/3790835/17111331/5752d0a6-525e-11e6-9a6b-cd20f7cca49c.jpg)

**Comment by laoneo** [comment]
@cpfeifer that's exactly what I use in the PR #96. But I think compress in production and none compact in development is enough.

**Comment by cpfeifer** [comment]
@laoneo - There are 3 provided in this library according to the docs:

> It’s possible to customize the formatting of the output CSS by changing the default formatter.
> 
> Three formatters are included:
> 
> scss_formatter
> scss_formatter_nested (default)
> scss_formatter_compressed

http://leafo.net/scssphp/docs/#compiling

It would not be difficult to have a user selectable option in the backend for the compression. I think that is a very useful option to include, I would use it.

**Comment by laoneo** [comment]
As we want to hide such functionality as much as possible from the end user, I would not offer them an option to do _nested_ formating of CSS code or similar. No average site admin will understand what that means. But having a development and production mode should be easier to understand. I see my self as an average site builder and I would never use different formating options. But a development mode and production mode do make sense to me.

**Comment by cpfeifer** [comment]
Just an idea. It wouldn't be difficult to implement and it can be useful, but it's not necessarily a highly requested feature.

**Comment by laoneo** [comment]
I agree, having a variable dump does have higher priority :smile: So I'm closing this one in favor of PR #96.
