### ISSUE TITLE
Lessphp / Less Compiler

### ISSUE THREAD

**Issue by zero-24** [Digital-Peak-Incubator/tpl_tauristar#93]
#### Steps to reproduce the issue

see: https://github.com/Digital-Peak-Incubator/tpl_tauristar/tree/tpl_tauristar/templates/tauristar/helpers/lessphp

#### Expected result

Use JLess (https://github.com/Digital-Peak-Incubator/tpl_tauristar/blob/tpl_tauristar/libraries/cms/less/less.php)

#### Actual result

We use lessphp from our helpers dir but there is a JLess API in the Core.

#### Additional comments

Do we have any reason to not use the JLess Class?

**Comment by yvesh** [comment]
@zero-24 In our last meeting we decided to use scss (you were there :P), so it's obsolete anyways.

**Comment by laoneo** [comment]
Did joomla 3.6 introduce sass compiler as library?

**Comment by laoneo** [comment]
To answer my own question, Joomla has no sass library in version 3.6, only supports to edit sass files joomla/joomla-cms#10186. I'm closing this one as we are moving to SASS #83.
